import React from "react";
import { useRerumObject } from "../../hooks/useRerumObject";
import { GeneratedBy } from "../GeneratedBy/GeneratedBy";
import styles from "./metadata.module.css";
import { usePath } from "../../hooks/usePath";
import classNames from "classnames";
import moment from "moment";

export const Metadata = () => {
  const { path: rerumId } = usePath();
  const { data, loading, error } = useRerumObject(rerumId);

  if (loading) return <div>Loading...</div>;

  if (error)
    return (
      <div className={styles.metadata}>
        <h3>Something went wrong</h3>
        <p>
          Error code:{" "}
          <span className={classNames(styles.mono, styles.red)}>
            {error.status}
          </span>
        </p>
        <p>
          Error message:{" "}
          <span className={classNames(styles.mono, styles.red)}>
            {error.info.split("\n").join(". ")}
          </span>
        </p>
      </div>
    );

  if (!data)
    return (
      <div className={styles.metadata}>
        <h3>No data exists</h3>
        <p>This rerum ID does not exist.</p>
      </div>
    );

  return (
    <div className={styles.metadata}>
      <h3 className={styles.sectionTitle}>Metadata</h3>
      <h4>Generated By</h4>
      <GeneratedBy rerumId={data.__rerum.generatedBy} />
      <h4 style={{ marginTop: 4 }}>Object Details</h4>
      <div>
        @id:{" "}
        <a className={styles.id} href={data["@id"]}>
          {data["@id"].split("/").pop()}
        </a>
        , Created at{" "}
        <span className={styles.mono}>
          {moment(data.__rerum.createdAt).format("M/D/YYYY")}
        </span>
      </div>
      {data.__rerum.history.next.length > 0 && (
        <div className={classNames(styles.alert, styles.danger)}>
          <strong>Warning:</strong> This rerum object has been superseded.
        </div>
      )}
      {data.__rerum.history.next.length === 0 && (
        <div className={classNames(styles.alert, styles.success)}>
          <strong>Note:</strong> This rerum object is the latest version.
        </div>
      )}
    </div>
  );
};
